FROM debian:latest
RUN apt update && apt -y upgrade
RUN apt-get update && apt-get -y upgrade
RUN apt install -y software-properties-common
RUN apt install -y git gcc gdb make wget gdb
CMD [ "/bin/bash" ]
