version: '3.9'
services:
  compile:
    tty: true
    build: 
      context: ../.docker
      dockerfile: Dockerfile
    image: skrjtech/compile:latest
    container_name: compile_run
    hostname: chost
    restart: always
    privileged: true
    volumes:
      - ..:/ws