version: '3.9'
services:
  algorithm:
    build: 
      context: ../.docker
      dockerfile: Dockerfile
    image: skrjtech/compiler:latest
    container_name: algorithm_run
    tty: true
    restart: always
    hostname: compiler
    privileged: true
    volumes:
      - ..:/HomeProjects