version: '3.9'
services:
  algorithm:
    build: 
      context: ../.docker
      dockerfile: Dockerfile
    image: skrjtech/compile:c
    container_name: algorithm_run
    tty: true
    restart: always
    hostname: chost
    privileged: true
    volumes:
      - ..:/ws